The background checker failed to report errors correctly.
This was caused by an API change in 0.32, which passes an
extra argument to report_error:

TypeError: report_error() takes exactly 2 arguments (3 given)