Fix Python 3 progress display
The `call_repeatedly` method no longer exists. Error was:

        self.update = tasks.get_loop().call_repeatedly(0.2, self.show_progress)
    AttributeError: '_UnixSelectorEventLoop' object has no attribute 'call_repeatedly'