Fix macOS CI failure
Error was:

    ==> Pouring python-3.7.6.high_sierra.bottle.tar.gz
    Error: The `brew link` step did not complete successfully
    The formula built, but is not symlinked into /usr/local
    Could not symlink Frameworks/Python.framework/Headers
    Target /usr/local/Frameworks/Python.framework/Headers
    is a symlink belonging to python@2. You can unlink it:
      brew unlink python@2

And also:

    pygobject was deleted from homebrew/core in commit fcfa254:
      pygobject: delete
      Does not support Python 3, and needs pygtk which has been removed.

The 0compile branch has now been updated to work with Python 3 and to
work without pygobject. This commit just avoids trying to install
pygobject.