Cope with a background update failing to find a solution
This could happen if a distribution package was updated to an incompatible
version, for example. We now try to show the GUI, and if that fails then we
show the error with a notification and give up.

The error was:

  File "/usr/lib/python2.7/site-packages/zeroinstall/injector/driver.py", line 68, in get_uncached_implementations
    impl = selection.impl
AttributeError: 'NoneType' object has no attribute 'impl'